import subprocess
import json
import os
from datetime import datetime
from pathlib import Path
 
REPO_PATH = "/home/ravikirannc29/repo/gcp-tf"  # update this to your actual repo path
 
 
def commit_fix_to_git(issue: dict, fix: dict) -> str:
    """Commits the fix decision (and YAML if present) to the git repo."""
 
    category = issue["category"].lower()
    folder_map = {
        "unattached_disk": "cost",
        "underutilized_vm": "cost",
        "high_disk_usage": "availability",
        "unencrypted_disk": "security",
        "open_ssh_port": "security"
    }
    folder = folder_map.get(category, "cost")
 
    filename = f"{fix['issue_id']}.yaml"
    filepath = Path(REPO_PATH) / "fixes" / folder / filename
 
    content = fix.get("crossplane_yaml")
    if not content:
        # No YAML means it's a delete/imperative action - log it as a record instead
        content = f"""# Action Record (no YAML - imperative action)
# Issue: {issue['description']}
# Root cause: {fix['root_cause']}
# Fix action: {fix['fix_action']}
# Risk level: {fix['risk_level']}
# Confidence: {fix['confidence']}
# Estimated impact: {fix['estimated_impact']}
# Timestamp: {datetime.utcnow().isoformat()}
"""
 
    filepath.parent.mkdir(parents=True, exist_ok=True)
    filepath.write_text(content)
 
    commit_msg = f"""fix({folder}): {fix['fix_action']} for {issue['category']}
 
Issue: {issue['description']}
Root cause: {fix['root_cause']}
Confidence: {fix['confidence']}%
Impact: {fix['estimated_impact']}
 
Auto-generated by SRE AI Agent
"""
 
    subprocess.run(["git", "-C", REPO_PATH, "add", str(filepath)], check=True)
    subprocess.run(["git", "-C", REPO_PATH, "commit", "-m", commit_msg], check=True)
    subprocess.run(["git", "-C", REPO_PATH, "push", "origin", "agent"], check=True)
 
    return str(filepath)
 
 
def execute_fix(issue: dict, fix: dict, auto_apply: bool = False) -> dict:
    """Executes the fix based on its type and risk level."""
 
    result = {
        "issue_id": fix["issue_id"],
        "status": "pending",
        "details": ""
    }
 
    # Step 1 - always commit to git first (audit trail)
    committed_path = commit_fix_to_git(issue, fix)
    result["git_commit_path"] = committed_path
 
    # Step 2 - decide whether to auto-apply based on risk
    if fix["risk_level"] == "LOW" and fix["confidence"] >= 80:
        should_apply = True
    else:
        should_apply = False
 
    if not should_apply or not auto_apply:
        result["status"] = "committed_only"
        result["details"] = "Fix committed to Git. Manual approval needed before applying."
        return result
 
    # Step 3 - apply the fix
    if fix["fix_action"] == "delete_disk":
        disk_name = issue["metadata"]["disk_name"]
        zone = issue["metadata"].get("zone", "us-central1-a")
 
        apply_result = subprocess.run([
            "gcloud", "compute", "disks", "delete", disk_name,
            f"--zone={zone}", "--quiet"
        ], capture_output=True, text=True)
 
        if apply_result.returncode == 0:
            result["status"] = "applied"
            result["details"] = f"Disk {disk_name} deleted successfully"
        else:
            result["status"] = "failed"
            result["details"] = apply_result.stderr
 
    elif fix.get("crossplane_yaml"):
        apply_result = subprocess.run(
            ["kubectl", "apply", "-f", "-"],
            input=fix["crossplane_yaml"],
            capture_output=True, text=True
        )
 
        if apply_result.returncode == 0:
            result["status"] = "applied"
            result["details"] = apply_result.stdout
        else:
            result["status"] = "failed"
            result["details"] = apply_result.stderr
 
    else:
        result["status"] = "unsupported_fix_type"
        result["details"] = f"No executor logic for action: {fix['fix_action']}"
 
    return result
 
 
if __name__ == "__main__":
    from detector_unattached_disks import UnattachedDiskDetector
    from ai_agent import analyse_issues
 
    print("Detecting issues...")
    detector = UnattachedDiskDetector()
    issues = detector.detect()
    print(f"Found {len(issues)} issue(s)\n")
 
    if not issues:
        print("No issues to process.")
        exit()
 
    print("Getting AI recommendations...")
    fixes = analyse_issues(issues)
 
    issue_map = {i["id"]: i for i in issues}
 
    for fix in fixes:
        issue = issue_map[fix["issue_id"]]
        print(f"\nProcessing: {issue['description']}")
        print(f"AI Decision: {fix['fix_action']} (confidence: {fix['confidence']}%)")
 
        result = execute_fix(issue, fix, auto_apply=True)
        print(f"Result: {json.dumps(result, indent=2)}")
