name: Terraform Destroy (GCP)

on:
  workflow_dispatch:   # manual trigger

permissions:
  id-token: write
  contents: read

env:
  TF_WORKING_DIR: gcp-simple-infra
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }}

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.14.7"

      - name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Terraform init
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}"

      - name: Terraform destroy
        run: terraform -chdir="${{ env.TF_WORKING_DIR }}" destroy -auto-approve
