
apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: bucket-1-ravikiran-nc-test
spec:
  forProvider:
    location: US
    uniformBucketLevelAccess: true
    iamConfiguration:
      uniformBucketLevelAccess:
        enabled: true
  providerConfigRef:
    name: gcp-provider
