apiVersion: compute.gcp.upbound.io/v1beta1
kind: Disk
metadata:
  name: disk-123
  annotations:
    crossplane.io/external-name: disk-123
    remediation.io/action: delete
spec:
  providerConfigRef:
    name: gcp-provider
  managementPolicies:
    - Observe
    - Delete
  forProvider:
    zone: us-central1-a
    sizeGb: 10
    type: pd-balanced
    project: sre-agent-hack