apiVersion: compute.gcp.upbound.io/v1beta1
kind: Disk
metadata:
  name: disk-123
spec:
  forProvider:
    size: 10
    type: pd-standard
    zone: us-central1-a
  providerConfigRef:
    name: gcp-provider
