
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Disk
metadata:
  name: disk-123
spec:
  forProvider:
    sizeGb: 10
    type: pd-standard
    zone: us-central1-a   # <-- update if needed
  providerConfigRef:
    name: gcp-provide
